version: '1.0'
name: fetch
displayName: fetch
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - main
  schedule:
    - cron: '* 0 */2 * * ? *'
variables:
  global:
    - GITHUB_TOKEN
    - TOKEN
stages:
  - name: fetchurl
    displayName: fetchurl
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: fetchurl
        displayName: fetchurl
        nodeVersion: 21.5.0
        commands:
          - git clone https://dream-deve:${TOKEN}@gitee.com/dream-deve/migu_video.git
          - '# git clone https://develop202:${GITHUB_TOKEN}@github.com/develop202/migu_video.git'
          - cd migu_video
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 执行编译命令 '
          - '# npm install && node fetchURLByWasm.js'
          - '# npm install && node fetchURLByAndroid.js'
          - '# npm install && node fetchURLByAndroidV2.js'
          - npm install && node fetchURLByAndroid720p.js
          - '# npm install && node fetchURLByWasmV2.js'
          - git config user.name "Gitee流水线"
          - git config user.email "actions@githee.com"
          - git add .
          - '# gitee流水线提交 '
          - git diff --quiet && git diff --staged --quiet || git commit -m "Update by Gitee流水线"
          - '# git push -f https://dream-deve:${TOKEN}@gitee.com/dream-deve/migu_video.git main:main'
          - git push
        strategy:
          retry: '0'
          timeout: 2
